remote_theme: pmarsceill/just-the-docs
title: ConsDev
description: Blog de Constantino Sorto - Arquitecto de Software - Catedrático de TI @ UNAH
url: "https://ConsSorto.github.io"

# Configuración del menú
nav_enabled: true
search_enabled: true

# Configuración del Buscador (Corregida la indentación)
search:
  button: "Buscar en ConsDev..."
  placeholder: "Escribe un tema (ej. Punteros)..."
  tokenizer_separator: '/[\s\-/]+/'

# Configuración de Mermaid
has_mermaid: true
mermaid:
  version: "10"

# Configuración del tema
color_scheme: dark