CREATE TABLE Estudiantes(
Id INTEGER PRIMARY KEY,
Nombre1 VARCHAR (100),
Nombre2 VARCHAR (100),
Apellido1 VARCHAR (100),
Apellido2 VARCHAR (100),
CarreraId INTEGER NOT NULL REFERENCES Carreras(Id)
);

CREATE TABLE Carreras(
    Id INTEGER PRIMARY KEY,
    Nombre VARCHAR UNIQUE
)